"""init

Revision ID: a71e95a49c0c
Revises: 
Create Date: 2026-05-28 20:26:12.357543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71e95a49c0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id_classroom', sa.String(), nullable=False),
    sa.Column('pavilion', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('allowed_radius', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_classroom')
    )
    op.create_table('groups_',
    sa.Column('id_group', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('knowledge_area',
    sa.Column('id_area', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_area')
    )
    op.create_table('periods',
    sa.Column('id_period', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_period'),
    sa.UniqueConstraint('year', 'cycle')
    )
    op.create_table('users',
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('courses',
    sa.Column('id_course', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_area', sa.String(), nullable=False),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['knowledge_area.id_area'], ),
    sa.PrimaryKeyConstraint('id_course')
    )
    op.create_table('teachers',
    sa.Column('id_teacher', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('teacher_card', sa.String(), nullable=False),
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('modifications_count', sa.Integer(), nullable=False),
    sa.Column('teacher_flag', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_teacher'),
    sa.UniqueConstraint('id_user'),
    sa.UniqueConstraint('teacher_card')
    )
    op.create_table('students',
    sa.Column('id_student', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('student_card', sa.String(), nullable=False),
    sa.Column('id_course', sa.String(), nullable=False),
    sa.Column('id_user', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('editable_fields', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_course'], ['courses.id_course'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_student'),
    sa.UniqueConstraint('id_user'),
    sa.UniqueConstraint('student_card')
    )
    op.create_table('subjects',
    sa.Column('id_subject', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_course', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_course'], ['courses.id_course'], ),
    sa.PrimaryKeyConstraint('id_subject')
    )
    op.create_table('classes',
    sa.Column('id_class', sa.String(), nullable=False),
    sa.Column('id_teacher', sa.String(), nullable=False),
    sa.Column('id_subject', sa.String(), nullable=False),
    sa.Column('id_group', sa.String(), nullable=False),
    sa.Column('id_period', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['groups_.id_group'], ),
    sa.ForeignKeyConstraint(['id_period'], ['periods.id_period'], ),
    sa.ForeignKeyConstraint(['id_subject'], ['subjects.id_subject'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id_teacher'], ),
    sa.PrimaryKeyConstraint('id_class')
    )
    op.create_table('enrollments',
    sa.Column('id_enrollment', sa.String(), nullable=False),
    sa.Column('id_student', sa.String(), nullable=False),
    sa.Column('id_class', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id_class'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.PrimaryKeyConstraint('id_enrollment'),
    sa.UniqueConstraint('id_student', 'id_class')
    )
    op.create_table('schedule',
    sa.Column('id_schedule', sa.String(), nullable=False),
    sa.Column('id_class', sa.String(), nullable=False),
    sa.Column('weekday', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', name='weekday'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', name='shift'), nullable=False),
    sa.Column('id_classroom', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id_class'], ),
    sa.ForeignKeyConstraint(['id_classroom'], ['classrooms.id_classroom'], ),
    sa.PrimaryKeyConstraint('id_schedule')
    )
    op.create_table('sessions',
    sa.Column('id_session', sa.String(), nullable=False),
    sa.Column('id_class', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('actual_start_time', sa.Time(), nullable=True),
    sa.Column('actual_end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'CANCELED', 'FINISHED', name='sessionstatus'), nullable=False),
    sa.Column('id_classroom', sa.String(), nullable=False),
    sa.Column('qr_token', sa.String(), nullable=False),
    sa.Column('qr_expires', sa.DateTime(), nullable=True),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('extended_mode', sa.Boolean(), nullable=False),
    sa.Column('extension_reason', sa.String(), nullable=True),
    sa.Column('close_notification_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_class'], ['classes.id_class'], ),
    sa.ForeignKeyConstraint(['id_classroom'], ['classrooms.id_classroom'], ),
    sa.PrimaryKeyConstraint('id_session'),
    sa.UniqueConstraint('qr_token')
    )
    op.create_table('attendance',
    sa.Column('id_attendance', sa.String(), nullable=False),
    sa.Column('id_session', sa.String(), nullable=False),
    sa.Column('id_student', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'JUSTIFIED', name='attendancestatus'), nullable=True),
    sa.Column('method', sa.Enum('QR', 'MANUAL', name='attendancemethod'), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('id_teacher_justifies', sa.String(), nullable=True),
    sa.Column('justification_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id_session'], ),
    sa.ForeignKeyConstraint(['id_student'], ['students.id_student'], ),
    sa.ForeignKeyConstraint(['id_teacher_justifies'], ['teachers.id_teacher'], ),
    sa.PrimaryKeyConstraint('id_attendance'),
    sa.UniqueConstraint('id_session', 'id_student')
    )
    op.create_table('teacher_flags',
    sa.Column('id_flag', sa.String(), nullable=False),
    sa.Column('id_teacher', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='flaglevel'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNDER_REVIEW', 'CLOSED', name='flagstatus'), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_teacher'], ['teachers.id_teacher'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id_session'], ),
    sa.PrimaryKeyConstraint('id_flag')
    )
    op.create_table('attendance_event',
    sa.Column('id_event', sa.String(), nullable=False),
    sa.Column('id_attendance', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CREATION', 'STATUS_CHANGE', 'JUSTIFICATION', name='eventtype'), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('id_actor', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_actor'], ['teachers.id_teacher'], ),
    sa.ForeignKeyConstraint(['id_attendance'], ['attendance.id_attendance'], ),
    sa.PrimaryKeyConstraint('id_event')
    )
    op.create_table('justification_attachment',
    sa.Column('id_attachment', sa.String(), nullable=False),
    sa.Column('id_attendance', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'PDF', name='attachmenttype'), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_attendance'], ['attendance.id_attendance'], ),
    sa.PrimaryKeyConstraint('id_attachment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('justification_attachment')
    op.drop_table('attendance_event')
    op.drop_table('teacher_flags')
    op.drop_table('attendance')
    op.drop_table('sessions')
    op.drop_table('schedule')
    op.drop_table('enrollments')
    op.drop_table('classes')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('courses')
    op.drop_table('users')
    op.drop_table('periods')
    op.drop_table('knowledge_area')
    op.drop_table('groups_')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
